version: '2'
services:
    jhauthserver-app:
        image: jhauthserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhauthserver-mysql:3306/jhauthserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhauthserver-mysql:
        extends:
            file: mysql.yml
            service: jhauthserver-mysql
